import { useEffect } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link } from 'expo-router';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { colors, radius, spacing, typography } from '../theme/tokens';
import { equipmentTypes, muscleGroups } from '../types/workout';
import { useWorkoutStore } from '../store/workout';
import { getWeeklyProgress } from '../utils/weeklyProgress';

const icons: Record<string, keyof typeof MaterialCommunityIcons.glyphMap> = { Pecho: 'arm-flex', Espalda: 'human', Bíceps: 'arm-flex', Tríceps: 'weight-lifter', Hombros: 'human-male', Piernas: 'run-fast', Core: 'meditation' };

export default function Home() {
  const { selectedMuscles, toggleMuscle, loadHistory, history, availableEquipment, toggleEquipment } = useWorkoutStore();
  useEffect(() => loadHistory(), [loadHistory]);
  const weeklyProgress = getWeeklyProgress(history);
  const workedThisWeek = new Set(weeklyProgress.trainedMuscles);
  const selectedLabel = selectedMuscles.length > 0 ? selectedMuscles.join(' + ') : 'SIN SELECCIÓN';
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
    <View style={styles.top}><View><Text style={styles.kicker}>MODO MAMADO / 01</Text><Text style={styles.title}>¿QUÉ TOCA{`\n`}HOY?</Text></View><Link href="/history" asChild><Pressable accessibilityLabel="Abrir historial" style={styles.iconButton}><MaterialCommunityIcons name="history" size={24} color={colors.text} /></Pressable></Link></View>
    <View style={styles.today}><View><Text style={styles.todayLabel}>HOY · {new Date().toLocaleDateString('es-CL', { weekday: 'short', day: 'numeric', month: 'short' }).toUpperCase()}</Text><Text style={styles.todayValue}>{selectedLabel}</Text></View><MaterialCommunityIcons name="lightning-bolt" size={30} color={colors.lime} /></View>
    <View style={styles.weekSummary}><View><Text style={styles.section}>ESTA SEMANA</Text><Text style={styles.weekTitle}>{weeklyProgress.workouts.length} ENTRENAMIENTO{weeklyProgress.workouts.length === 1 ? '' : 'S'}</Text></View><MaterialCommunityIcons name="calendar-check" size={27} color={colors.lime} /><Text style={styles.weekMessage}>{weeklyProgress.recommendedMuscles.length > 0 ? `SIGUIENTE: ${weeklyProgress.recommendedMuscles.slice(0, 2).join(' + ').toUpperCase()}` : 'TODOS LOS GRUPOS REGISTRADOS'}</Text></View>
    <Text style={styles.section}>ELIGE UNO O MÁS GRUPOS</Text><Text style={styles.helper}>Seleccionados: {selectedMuscles.length}. Puedes combinar pecho, espalda, core y más.</Text><View style={styles.grid}>{muscleGroups.map((muscle) => { const isSelected = selectedMuscles.includes(muscle); const wasWorked = workedThisWeek.has(muscle); return <Pressable key={muscle} onPress={() => toggleMuscle(muscle)} accessibilityRole="button" accessibilityState={{ selected: isSelected }} style={[styles.muscle, isSelected && styles.muscleActive]}><MaterialCommunityIcons name={icons[muscle]} size={27} color={isSelected ? colors.background : colors.lime} /><Text style={[styles.muscleName, isSelected && styles.muscleNameActive]}>{muscle.toUpperCase()}</Text><Text style={[styles.muscleMeta, isSelected && styles.muscleNameActive]}>{isSelected ? 'SELECCIONADO' : wasWorked ? 'HECHO ESTA SEMANA' : 'DISPONIBLE'}</Text></Pressable>; })}</View>
    <Text style={styles.section}>EQUIPAMIENTO DISPONIBLE HOY</Text><Text style={styles.helper}>Se usa para sugerir sustitutos si un ejercicio no aplica.</Text><View style={styles.chipRow}>{equipmentTypes.map((equipment) => { const isAvailable = availableEquipment.includes(equipment); return <Pressable key={equipment} onPress={() => toggleEquipment(equipment)} accessibilityRole="button" accessibilityState={{ selected: isAvailable }} style={[styles.chip, isAvailable && styles.chipActive]}><Text style={[styles.chipText, isAvailable && styles.chipTextActive]}>{equipment.toUpperCase()}</Text></Pressable>; })}</View>
    <View style={styles.ctaRow}><View><Text style={styles.section}>LISTO PARA EMPEZAR</Text><Text style={styles.ctaSub}>Tu rutina tendrá {selectedMuscles.length} grupo{selectedMuscles.length === 1 ? '' : 's'}.</Text></View><Link href="/routine" asChild><Pressable style={selectedMuscles.length === 0 ? styles.startDisabled : styles.start} disabled={selectedMuscles.length === 0} accessibilityRole="button"><Text style={styles.startText}>VER RUTINA</Text><MaterialCommunityIcons name="arrow-right" size={20} color={colors.background} /></Pressable></Link></View>
    {history[0] && <Text style={styles.last}>ÚLTIMO: {history[0].muscleGroups.join(' + ').toUpperCase()} · COMPLETADO</Text>}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, paddingTop: spacing.md, gap: spacing.lg }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, kicker: { color: colors.lime, fontFamily: 'Quantico', fontSize: 12, letterSpacing: 1 }, title: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 36, lineHeight: 38, marginTop: spacing.sm }, iconButton: { width: 48, height: 48, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm }, today: { padding: spacing.md, borderLeftWidth: 3, borderLeftColor: colors.lime, backgroundColor: colors.surface, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, todayLabel: { color: colors.muted, fontFamily: 'Quantico', fontSize: 11 }, todayValue: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 18, marginTop: 4 }, weekSummary: { padding: spacing.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: spacing.sm }, weekTitle: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 20, marginTop: 4 }, weekMessage: { color: colors.lime, fontFamily: 'Quantico', fontSize: 11 }, section: { color: colors.muted, fontFamily: 'Quantico', fontSize: 12, letterSpacing: 1 }, helper: { color: colors.muted, fontSize: 13, marginTop: -12 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, muscle: { width: '31%', minHeight: 105, padding: spacing.sm, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, justifyContent: 'space-between' }, muscleActive: { backgroundColor: colors.lime, borderColor: colors.lime }, muscleName: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 12 }, muscleNameActive: { color: colors.background }, muscleMeta: { color: colors.muted, fontFamily: 'Quantico', fontSize: 9 }, chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, chip: { paddingVertical: spacing.xs, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, backgroundColor: colors.card }, chipActive: { backgroundColor: colors.lime, borderColor: colors.lime }, chipText: { color: colors.muted, fontFamily: 'Quantico', fontSize: 10 }, chipTextActive: { color: colors.background }, ctaRow: { paddingTop: spacing.sm, gap: spacing.md }, ctaSub: { color: colors.muted, ...typography.body, marginTop: 4 }, start: { backgroundColor: colors.lime, minHeight: 58, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, borderRadius: radius.sm }, startDisabled: { opacity: 0.4 }, startText: { color: colors.background, fontFamily: 'QuanticoBold', fontSize: 14 }, last: { color: colors.lime, fontFamily: 'Quantico', fontSize: 11, textAlign: 'center' } });