import { useEffect } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link } from 'expo-router';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { colors, radius, spacing, typography } from '../theme/tokens';
import { muscleGroups } from '../types/workout';
import { useWorkoutStore } from '../store/workout';

const icons: Record<string, keyof typeof MaterialCommunityIcons.glyphMap> = { Pecho: 'arm-flex', Espalda: 'human', Bíceps: 'arm-flex', Tríceps: 'weight-lifter', Hombros: 'human-male', Piernas: 'run-fast', Core: 'meditation' };

export default function Home() {
  const { selectedMuscle, selectMuscle, loadHistory, history } = useWorkoutStore();
  useEffect(() => loadHistory(), [loadHistory]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
    <View style={styles.top}><View><Text style={styles.kicker}>MODO MAMADO / 01</Text><Text style={styles.title}>¿QUÉ TOCA{`\n`}HOY?</Text></View><Link href="/history" asChild><Pressable accessibilityLabel="Abrir historial" style={styles.iconButton}><MaterialCommunityIcons name="history" size={24} color={colors.text} /></Pressable></Link></View>
    <View style={styles.today}><View><Text style={styles.todayLabel}>HOY · {new Date().toLocaleDateString('es-CL', { weekday: 'short', day: 'numeric', month: 'short' }).toUpperCase()}</Text><Text style={styles.todayValue}>{selectedMuscle}</Text></View><MaterialCommunityIcons name="lightning-bolt" size={30} color={colors.lime} /></View>
    <Text style={styles.section}>ELIGE TU OBJETIVO</Text><View style={styles.grid}>{muscleGroups.map((muscle) => <Pressable key={muscle} onPress={() => selectMuscle(muscle)} accessibilityRole="button" accessibilityState={{ selected: selectedMuscle === muscle }} style={[styles.muscle, selectedMuscle === muscle && styles.muscleActive]}><MaterialCommunityIcons name={icons[muscle]} size={27} color={selectedMuscle === muscle ? colors.background : colors.lime} /><Text style={[styles.muscleName, selectedMuscle === muscle && styles.muscleNameActive]}>{muscle.toUpperCase()}</Text><Text style={[styles.muscleMeta, selectedMuscle === muscle && styles.muscleNameActive]}>{selectedMuscle === muscle ? 'SELECCIONADO' : 'PREPARAR'}</Text></Pressable>)}</View>
    <View style={styles.ctaRow}><View><Text style={styles.section}>LISTO PARA EMPEZAR</Text><Text style={styles.ctaSub}>Tu rutina te está esperando.</Text></View><Link href="/routine" asChild><Pressable style={styles.start} accessibilityRole="button"><Text style={styles.startText}>VER RUTINA</Text><MaterialCommunityIcons name="arrow-right" size={20} color={colors.background} /></Pressable></Link></View>
    {history[0] && <Text style={styles.last}>ÚLTIMO: {history[0].muscleGroup.toUpperCase()} · COMPLETADO</Text>}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, paddingTop: spacing.md, gap: spacing.lg }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, kicker: { color: colors.lime, fontFamily: 'Quantico', fontSize: 12, letterSpacing: 1 }, title: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 36, lineHeight: 38, marginTop: spacing.sm }, iconButton: { width: 48, height: 48, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm }, today: { padding: spacing.md, borderLeftWidth: 3, borderLeftColor: colors.lime, backgroundColor: colors.surface, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, todayLabel: { color: colors.muted, fontFamily: 'Quantico', fontSize: 11 }, todayValue: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 22, marginTop: 4 }, section: { color: colors.muted, fontFamily: 'Quantico', fontSize: 12, letterSpacing: 1 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, muscle: { width: '31%', minHeight: 105, padding: spacing.sm, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, justifyContent: 'space-between' }, muscleActive: { backgroundColor: colors.lime, borderColor: colors.lime }, muscleName: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 12 }, muscleNameActive: { color: colors.background }, muscleMeta: { color: colors.muted, fontFamily: 'Quantico', fontSize: 9 }, ctaRow: { paddingTop: spacing.sm, gap: spacing.md }, ctaSub: { color: colors.muted, ...typography.body, marginTop: 4 }, start: { backgroundColor: colors.lime, minHeight: 58, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, borderRadius: radius.sm }, startText: { color: colors.background, fontFamily: 'QuanticoBold', fontSize: 14 }, last: { color: colors.lime, fontFamily: 'Quantico', fontSize: 11, textAlign: 'center' } });