import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { routines } from '../data/routines';
import { colors, radius, spacing, typography } from '../theme/tokens';
import { useWorkoutStore } from '../store/workout';

export default function Routine() {
  const { selectedMuscle, startWorkout } = useWorkoutStore();
  const exercises = routines[selectedMuscle];
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
    <Pressable onPress={() => router.back()} style={styles.back}><MaterialCommunityIcons name="arrow-left" size={22} color={colors.text} /><Text style={styles.backText}>VOLVER</Text></Pressable>
    <Text style={styles.kicker}>RUTINA SUGERIDA / {exercises.length} EJERCICIOS</Text><Text style={styles.title}>{selectedMuscle.toUpperCase()}</Text><Text style={styles.subtitle}>Hoy no toca pensar. Solo ejecutar.</Text>
    <View style={styles.list}>{exercises.map((item, index) => <View key={item.id} style={styles.exercise}><View style={styles.number}><Text style={styles.numberText}>{String(index + 1).padStart(2, '0')}</Text></View><View style={styles.info}><Text style={styles.name}>{item.name}</Text><Text style={styles.detail}>{item.equipment.toUpperCase()} · {item.restSeconds}s DESCANSO</Text></View><View style={styles.prescription}><Text style={styles.sets}>{item.sets}</Text><Text style={styles.reps}>SERIES · {item.reps} REPS</Text></View></View>)}</View>
    <View style={styles.note}><MaterialCommunityIcons name="information-outline" color={colors.lime} size={20} /><Text style={styles.noteText}>Calienta antes de empezar. La técnica manda.</Text></View>
    <Pressable onPress={() => { startWorkout(); router.push('/workout'); }} style={styles.start}><Text style={styles.startText}>COMENZAR ENTRENAMIENTO</Text><MaterialCommunityIcons name="arrow-right" size={21} color={colors.background} /></Pressable>
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, gap: spacing.lg }, back: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, backText: { color: colors.text, fontFamily: 'Quantico', fontSize: 12 }, kicker: { color: colors.lime, fontFamily: 'Quantico', fontSize: 12, letterSpacing: 1 }, title: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 38, marginTop: -10 }, subtitle: { color: colors.muted, ...typography.body, marginTop: -10 }, list: { gap: spacing.sm }, exercise: { minHeight: 92, backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: radius.sm, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, number: { width: 34, height: 34, backgroundColor: colors.limeDim, justifyContent: 'center', alignItems: 'center' }, numberText: { color: colors.lime, fontFamily: 'QuanticoBold' }, info: { flex: 1, gap: 6 }, name: { color: colors.text, fontFamily: 'QuanticoBold', fontSize: 16 }, detail: { color: colors.muted, fontFamily: 'Quantico', fontSize: 9 }, prescription: { alignItems: 'flex-end' }, sets: { color: colors.lime, fontFamily: 'QuanticoBold', fontSize: 25 }, reps: { color: colors.muted, fontFamily: 'Quantico', fontSize: 8, textAlign: 'right' }, note: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center', padding: spacing.md, backgroundColor: colors.surface }, noteText: { flex: 1, color: colors.muted, fontSize: 13 }, start: { minHeight: 60, backgroundColor: colors.lime, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: spacing.sm, borderRadius: radius.sm }, startText: { color: colors.background, fontFamily: 'QuanticoBold', fontSize: 13 } });